spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plataforma_conversacional_dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: DEBUG
    com.plataforma.conversacional: TRACE
